### ISSUE TITLE
Module not found: Error: Can't resolve 'nest-raven' in v6.0.0-alpha.x

### ISSUE THREAD

**Issue by sergio-dreamcode** [mentos1386/nest-raven#105]
Currently I have some NestJS services using `nest-raven` and in the latest build it failed with Webpack errors complaining that `nest-raven` module can't be resolved. It happens for all `v6.0.0-alpha.x` packages.

## Steps to reproduce
```
npm init
npm install --save nest-raven@v6.0.0-alpha.2
node
> require.resolve('nest-raven')
Uncaught Error: Cannot find module 'nest-raven'
Require stack:
- <repl>
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.resolve (internal/modules/cjs/helpers.js:83:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '<repl>' ]
}
```

## Extra information
I checked the `node_modules/nest-raven` directory and the `nest-raven` directory exists with this structure:
```
├── LICENSE
├── README.md
├── lib
│   ├── index.d.ts
│   ├── index.js
│   ├── ...
├── package.json
└── test
    ... 
```

However by checking a cached project where everything worked we had the next structure in `node_modules/nest-raven`:
```
├── dist
│   ├── index.d.ts
│   ├── index.js
│   ├── ...
├── LICENSE
├── package.json
└── README.md

```

**Comment by sergio-dreamcode** [comment]
I'm really sorry, I was checking what could be the cause and forgot I am using a private NPM registry that also caches from npmjs.com.

It was an issue with cache, of course it failed in my local and deployment machines because they use the same NPM registry. I will close this issue.
