### ISSUE TITLE
(0 , hub_1.withScope) is not a function

### ISSUE THREAD

**Issue by artem-tkachuk** [mentos1386/nest-raven#552]
Hello!

I am facing this error when using `nest-raven`:

```shell
[Nest] 24024  - 05/31/2023, 9:48:21 AM   ERROR [ExceptionsHandler] (0 , hub_1.withScope) is not a function
TypeError: (0 , hub_1.withScope) is not a function at Object.error (/path/to/your/project/api/node_modules/nest raven/dist/raven.interceptor.js:34:41)
    at /path/to/your/project/api/node_modules/rxjs/src/internal/operators/tap.ts:199:32
    at OperatorSubscriber._this._error (/path/to/your/project/api/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:79:13)
    at OperatorSubscriber.Subscriber.error (/path/to/your/project/api/node_modules/rxjs/src/internal/Subscriber.ts:91:12)
    at OperatorSubscriber.Subscriber._error (/path/to/your/project/api/node_modules/rxjs/src/internal/Subscriber.ts:124:24)
    at OperatorSubscriber.Subscriber.error (/path/to/your/project/api/node_modules/rxjs/src/internal/Subscriber.ts:91:12)
    at OperatorSubscriber.Subscriber._error (/path/to/your/project/api/node_modules/rxjs/src/internal/Subscriber.ts:124:24)
    at OperatorSubscriber.Subscriber.error (/path/to/your/project/api/node_modules/rxjs/src/internal/Subscriber.ts:91:12)
    at OperatorSubscriber.Subscriber._error (/path/to/your/project/api/node_modules/rxjs/src/internal/Subscriber.ts:124:24)
    at OperatorSubscriber.Subscriber.error (/path/to/your/project/api/node_modules/rxjs/src/internal/Subscriber.ts:91:12)
``` 

By Googling I found that this issue is similar to this, however, updating `@sentry/node` does not help. What does help is changing `withScope` to `Scope` in the compiled JS . Please see screenshot: there is no `withScope` function, only `Scope`. When I perform that change, everything works.
![Screenshot 2023-05-31 at 03 14 36](https://github.com/mentos1386/nest-raven/assets/45192056/f4262917-7c5e-43fb-8aaa-0f20c6205501)

I went ahead and cloned the package repo locally, compiled it into JS, and everything works. However, the compiled package code (screenshot below) looks different than what is in the actual project I am working on (which is on the first screenshot). 
![Screenshot 2023-05-31 at 03 17 26](https://github.com/mentos1386/nest-raven/assets/45192056/3988172a-3e68-48d7-b537-7def682dd5a6)
Both seem to be the latest versions of the package. Why might that discrepancy be and how do I fix this issue? 

I would appreciate any advice or pointers! Thank you very much in advance!

**Comment by artem-tkachuk** [comment]
Resolved by these versioning updates in our `package.json`:

<img width="474" alt="Screenshot 2023-05-31 at 21 33 59" src="https://github.com/mentos1386/nest-raven/assets/45192056/c0ee23ca-99a5-45ef-9034-01a8436dce98">
