### ISSUE TITLE
Cannot find module '@nestjs/graphql'

### ISSUE THREAD

**Issue by ymoreiratiti** [mentos1386/nest-raven#58]
When create a new project and import **RavenModule** in **app.module.ts** an error appears. 

```shell
[12:05:29] Starting compilation in watch mode...

[12:05:34] Found 0 errors. Watching for file changes.

internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module '@nestjs/graphql'
Require stack:
- C:\Temp\starterkit\api\node_modules\nest-raven\dist\raven.interceptor.js
- C:\Temp\starterkit\api\node_modules\nest-raven\dist\index.js
- C:\Temp\starterkit\api\dist\src\app.module.js
- C:\Temp\starterkit\api\dist\src\main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Temp\starterkit\api\node_modules\nest-raven\dist\raven.interceptor.js:36:19)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Temp\\starterkit\\api\\node_modules\\nest-raven\\dist\\raven.interceptor.js',
    'C:\\Temp\\starterkit\\api\\node_modules\\nest-raven\\dist\\index.js',
    'C:\\Temp\\starterkit\\api\\dist\\src\\app.module.js',
    'C:\\Temp\\starterkit\\api\\dist\\src\\main.js'
  ]
}
```

My project doesn't use graphql.

Installing the npm packages seems to resolve de issue

**Comment by mentos1386** [comment]
Hey. Sadly `@nestjs/graphql` is required even if you do not use the gaphql part of the nest-raven.

We should in the future to make `@nestjs/graphql` optional dependency and required only when using the graphql logic.

**Comment by si-hyeon-ee** [comment]
The installation of @nestjs/grpahql requires enormous sub-dependencies and it makes the project heavy.
I don't use graphql at all, but I'm installing @nestjs/graphql for nest-raven, and hope this fixes soon.
thank you. maintainer!

**Comment by 9renpoto** [comment]
Hello @mentos1386 ( cc @ymoreiratiti , @si-hyeon-ee ) , I tried to fix it, can you give me a review?

**Comment by si-hyeon-ee** [comment]
@9renpoto  awesome  👍  i will check it as soon as possible
